handlers:
  - url: /
    static_files: frontend/ebay-search/build/index.html
    upload: frontend/ebay-search/build/index.html

  - url: /
    static_dir: frontend/ebay-search/build

runtime: nodejs20

